/-
Comparator challenge file: the headline theorems of `BranchingProcess`, restated
with `sorry` in place of their proofs.

Everything these statements mention is defined below, over Mathlib alone. No
module of the library is imported: the trust boundary of the audit is this file
together with its import closure, and the library is what the audit is about.
`Solution.lean` is the untrusted side and may import it freely.

Two statements carry the reduced and the conjugate law as a hypothesis, `θ'`
with `∀ k, θ' k = θ.skeletonWeight k`, rather than a bundled `Offspring` built
here. The bundling needs the weights to sum to one, which is a binomial
identity; carrying the law as a hypothesis keeps that proof out of the trusted
file and states the same mathematics.

Run the audit from the project root with `./comparator-audit.sh`; the audited
names are listed in `comparator-config.json`.
-/
import Mathlib
namespace Challenge

open MeasureTheory ProbabilityTheory
open scoped ENNReal

/-! ## The ambient tree and its subtrees -/

/-- A vertex of the ambient `N`-ary tree: a finite word over `Fin N`, the root
being the empty word and the children of `v` the words `v ++ [j]`. -/
abbrev Word (N : ℕ) : Type := List (Fin N)

/-- A subtree of the ambient tree: a prefix-closed set of words. -/
abbrev Subtree (N : ℕ) : Type := Descriptive.tree (Fin N)

/-- The measurable structure on subtrees: the one generated by the vertex events
`{T | v ∈ T}`. -/
instance Subtree.instMeasurableSpace {N : ℕ} : MeasurableSpace (Subtree N) :=
  MeasurableSpace.generateFrom {s | ∃ v : Word N, s = {T : Subtree N | v ∈ T}}

/-! ## Offspring laws -/

/-- An offspring distribution with support in `{0,…,J}`. -/
structure Offspring (J : ℕ) where
  /-- The mass function `j ↦ θ_j`. -/
  mass : ℕ → ℝ
  /-- Masses are nonnegative. -/
  nonneg : ∀ j, 0 ≤ mass j
  /-- The support lies in `{0,…,J}`. -/
  vanishing : ∀ j, J < j → mass j = 0
  /-- The masses sum to one. -/
  total : ∑ j ∈ Finset.range (J + 1), mass j = 1

instance {J : ℕ} : CoeFun (Offspring J) (fun _ => ℕ → ℝ) := ⟨Offspring.mass⟩

namespace Offspring

variable {J : ℕ} (θ : Offspring J)

/-- The mean offspring number `m = ∑_j j θ_j`. -/
noncomputable def mean : ℝ := ∑ j ∈ Finset.range (J + 1), (j : ℝ) * θ j

/-- A law is subcritical when its mean is below one. -/
def IsSubcritical : Prop := mean θ < 1

/-- The generating function `f(s) = ∑_{j=0}^{J} θ_j s^j`. -/
noncomputable def gen (s : ℝ) : ℝ := ∑ j ∈ Finset.range (J + 1), θ j * s ^ j

/-- The fixed points of the generating function in `[0,1]`. -/
def fixedSet : Set ℝ := {s | s ∈ Set.Icc (0 : ℝ) 1 ∧ gen θ s = s}

/-- The extinction probability `q = inf {s ∈ [0,1] : f(s) = s}`, the least fixed
point of the generating function in `[0,1]`. -/
noncomputable def extinction : ℝ := sInf θ.fixedSet

/-- The surviving-children weights `∑_j θ_j C(j,k) (1-q)^k q^{j-k}`. -/
noncomputable def surviveWeight (k : ℕ) : ℝ :=
  ∑ j ∈ Finset.range (J + 1),
    θ j * (j.choose k : ℝ) * (1 - θ.extinction) ^ k * θ.extinction ^ (j - k)

/-- The Harris-Sevastyanov transform: the surviving-children weights renormalised
by the survival probability `1-q`, and zero at `k = 0`. -/
noncomputable def skeletonWeight (k : ℕ) : ℝ :=
  if k = 0 then 0 else θ.surviveWeight k / (1 - θ.extinction)

/-- The conjugate weights `θ_j q^j / q`. -/
noncomputable def conjugateWeight (j : ℕ) : ℝ := θ j * θ.extinction ^ j / θ.extinction

/-- The offspring law read as a probability mass function on `ℕ`. -/
noncomputable def toPMF : PMF ℕ :=
  ⟨fun j ↦ ENNReal.ofReal (θ j), by
    have hzero : ∀ j ∉ Finset.range (J + 1), ENNReal.ofReal (θ j) = 0 := by
      intro j hj
      rw [Finset.mem_range] at hj
      rw [θ.vanishing j (by omega), ENNReal.ofReal_zero]
    have hsum : HasSum (fun j ↦ ENNReal.ofReal (θ j))
        (∑ j ∈ Finset.range (J + 1), ENNReal.ofReal (θ j)) :=
      hasSum_sum_of_ne_finset_zero hzero
    rwa [← ENNReal.ofReal_sum_of_nonneg (fun j _ ↦ θ.nonneg j), θ.total,
      ENNReal.ofReal_one] at hsum⟩

/-- The one-vertex law: the measure on `ℕ` with mass `θ_j` at `j`. -/
noncomputable def law : Measure ℕ := θ.toPMF.toMeasure

instance isProbabilityMeasure_law : IsProbabilityMeasure θ.law :=
  inferInstanceAs (IsProbabilityMeasure θ.toPMF.toMeasure)

end Offspring

/-! ## The sample of an offspring field -/

variable {J N : ℕ}

/-- The tree cut out by a field `c` of offspring counts: the vertex `v` keeps its
children `v ++ [j]` with `j < c v`. -/
def sample (c : Word N → ℕ) : Subtree N :=
  ⟨{v | ∀ i, (h : i < v.length) → ((v.get ⟨i, h⟩ : Fin N) : ℕ) < c (v.take i)}, by
    intro v a hv i hi
    have hi' : i < (v ++ [a]).length := by
      rw [List.length_append]
      omega
    have h : (((v ++ [a])[i]'hi' : Fin N) : ℕ) < c ((v ++ [a]).take i) := hv i hi'
    rw [List.getElem_append_left hi, List.take_append_of_le_length hi.le] at h
    exact h⟩

/-- Survival of the sample of `c`: the tree it cuts out is infinite. -/
def Survives (c : Word N → ℕ) : Prop := (sample c : Set (Word N)).Infinite

open scoped Classical in
/-- The children of the root founding an infinite subtree. -/
noncomputable def survivors (c : Word N → ℕ) : Finset (Fin N) :=
  Finset.univ.filter fun i : Fin N ↦ (i : ℕ) < c [] ∧ Survives fun w ↦ c (i :: w)

/-- The number of surviving children of the root. -/
noncomputable def skeletonDegree (c : Word N → ℕ) : ℕ := (survivors c).card

/-- The letters naming a child of a root with `j` children. -/
def childSet (N j : ℕ) : Finset (Fin N) := Finset.univ.filter fun i : Fin N ↦ (i : ℕ) < j

/-- The offspring field of the `m`-th child subtree of a root whose children of
interest are named by `S`, the children ordered by the alphabet; the zero field
when there are at most `m` of them. -/
noncomputable def bushOf (S : Finset (Fin N)) (m : ℕ) (c : Word N → ℕ) : Word N → ℕ :=
  if h : m < S.card then (fun w ↦ c (S.orderEmbOfFin rfl ⟨m, h⟩ :: w)) else fun _ ↦ 0

/-- The `m`-th surviving subtree of the root. -/
noncomputable def bushAt (c : Word N → ℕ) (m : ℕ) : Word N → ℕ := bushOf (survivors c) m c

/-- The `m`-th dying subtree of the root, in letter order. -/
noncomputable def dyingAt (c : Word N → ℕ) (m : ℕ) : Word N → ℕ :=
  bushOf (childSet N (c []) \ survivors c) m c

/-- The field of the subtree an address leads to along surviving children. -/
noncomputable def skelSub : (Word N → ℕ) → Word N → (Word N → ℕ)
  | c, [] => c
  | c, (j :: u) => skelSub (bushAt c j) u

/-- The offspring field of the skeleton, re-addressed so that the `m`-th
surviving child of a skeleton vertex is reached by the letter `m`. -/
noncomputable def skelField (c : Word N → ℕ) : Word N → ℕ := fun u ↦ skeletonDegree (skelSub c u)

/-- The skeleton, re-addressed: the tree cut out by the offspring field of the
skeleton. -/
noncomputable def skelTree (c : Word N → ℕ) : Subtree N := sample (skelField c)

/-! ## The laws -/

/-- The i.i.d. field measure: the infinite product on `ι → α` of copies of `μ`. -/
noncomputable def fieldMeasure {ι : Type*} {α : Type*} [MeasurableSpace α] (μ : Measure α)
    [IsProbabilityMeasure μ] : Measure (ι → α) :=
  Measure.infinitePi (fun _ : ι ↦ μ)

/-- The law of the offspring field: the coordinates are i.i.d. with law `θ`. -/
noncomputable def sampleMeasure (θ : Offspring J) : Measure (Word N → ℕ) :=
  fieldMeasure θ.law

/-- The law of the offspring field conditioned on survival. -/
noncomputable def survivalMeasure (θ : Offspring J) : Measure (Word N → ℕ) :=
  ProbabilityTheory.cond (sampleMeasure θ) {c : Word N → ℕ | Survives c}

/-- The law of the offspring field conditioned on extinction. -/
noncomputable def bushMeasure (θ : Offspring J) : Measure (Word N → ℕ) :=
  ProbabilityTheory.cond (sampleMeasure θ) {c : Word N → ℕ | ¬ Survives c}

/-- The law of the Galton-Watson tree of an offspring law. -/
noncomputable def treeLaw (θ : Offspring J) : Measure (Subtree N) :=
  (sampleMeasure θ).map sample

/-- The law of the re-addressed skeleton of a sample conditioned to survive. -/
noncomputable def skeletonTreeLaw (θ : Offspring J) : Measure (Subtree N) :=
  (survivalMeasure θ).map skelTree

/-- The law of the tree of a sample conditioned to die. -/
noncomputable def bushTreeLaw (θ : Offspring J) : Measure (Subtree N) :=
  (bushMeasure θ).map sample

/-- The decoration of the root: `j` children of which `k` survive, the dying
subtrees constrained by their rank. -/
def decorationEvent (j k : ℕ) (B : ℕ → Set (Word N → ℕ)) : Set (Word N → ℕ) :=
  ({c : Word N → ℕ | c [] = j} ∩ {c : Word N → ℕ | skeletonDegree c = k})
    ∩ {c : Word N → ℕ | ∀ m : ℕ, m < j - k → dyingAt c m ∈ B m}

/-! ## Coarse geometry -/

section Geometry

open SimpleGraph

variable {V V' : Type*}

/-- `f` is a `D`-quasi-isometry from `G` to `G'`: all three constants equal to
`D`, the lower bound carried in the subtraction-free form `d ≤ D d' + D²`. -/
structure IsQIWith (D : ℕ) (G : SimpleGraph V) (G' : SimpleGraph V') (f : V → V') : Prop where
  /-- The upper bound. -/
  upper : ∀ x y, G'.dist (f x) (f y) ≤ D * G.dist x y + D
  /-- The lower bound. -/
  lower : ∀ x y, G.dist x y ≤ D * G'.dist (f x) (f y) + D * D
  /-- The image is `D`-dense. -/
  dense : ∀ y', ∃ x, G'.dist (f x) y' ≤ D

/-- `G` and `G'` are quasi-isometric: some map is a `D`-quasi-isometry for
some `D`. -/
def QuasiIsometric (G : SimpleGraph V) (G' : SimpleGraph V') : Prop :=
  ∃ (D : ℕ) (f : V → V'), IsQIWith D G G' f

/-- A ray: a map `ℕ → V` isometric onto its image. -/
def IsRay (G : SimpleGraph V) (r : ℕ → V) : Prop :=
  ∀ m n, G.dist (r m) (r n) = Nat.dist m n

/-- A line: a map `ℤ → V` isometric onto its image. -/
def IsLine (G : SimpleGraph V) (l : ℤ → V) : Prop :=
  ∀ m n, G.dist (l m) (l n) = (m - n).natAbs

/-- A hair at `c` of depth `h`: a component of the complement of `{c}` whose
vertices are within `h` of `c`, with one at exactly `h`. -/
def IsHair (G : SimpleGraph V) (c : V) (P : Set V) (h : ℕ) : Prop :=
  (∃ C : G.ComponentCompl ({c} : Set V), (C : Set V) = P) ∧
    (∀ v ∈ P, G.dist v c ≤ h) ∧ ∃ v ∈ P, G.dist v c = h

/-- The ray `ℕ` with the path-graph structure. -/
def rayGraph : SimpleGraph ℕ where
  Adj m n := m + 1 = n ∨ n + 1 = m
  symm := ⟨by intro a b h; omega⟩
  loopless := ⟨by intro a h; omega⟩

end Geometry

/-! ## The audited statements -/

/-- **The extinction probability is the probability of extinction**: the sample
of an offspring field is finite with probability `q`, the least fixed point of
the generating function in `[0,1]`. -/
theorem audit_sample_extinction {J N : ℕ} (θ : Offspring J) (hJN : J ≤ N) :
    sampleMeasure (N := N) θ {c : Word N → ℕ | ¬ Survives c}
      = ENNReal.ofReal θ.extinction := sorry

/-- **The Harris recursion**: conditioned on survival, the re-addressed skeleton
of the sample is a Galton-Watson tree with the reduced law, the weights of the
Harris-Sevastyanov transform. -/
theorem audit_skeleton_tree_law {J N : ℕ} (θ θ' : Offspring J) (hJN : J ≤ N)
    (hq : θ.extinction < 1) (hθ' : ∀ k, θ' k = θ.skeletonWeight k) :
    skeletonTreeLaw (N := N) θ = treeLaw (N := N) θ' := sorry

/-- **The bushes are Galton-Watson trees with the conjugate law**: conditioned on
extinction, the sample is a Galton-Watson tree for the tilted law `θ_j q^j / q`. -/
theorem audit_bush_tree_law {J N : ℕ} (θ θ' : Offspring J) (hJN : J ≤ N)
    (hq0 : 0 < θ.extinction) (hθ' : ∀ j, θ' j = θ.conjugateWeight j) :
    bushTreeLaw (N := N) θ = treeLaw (N := N) θ' := sorry

/-- **The joint Harris decomposition**: conditioned on survival, probing the
skeleton on a finite prefix-closed set of addresses and constraining the
decoration of each probed vertex, the mass factorises into one decoration weight
per vertex, each carrying its dying subtrees as independent conjugate samples. -/
theorem audit_harris_decorations {J N : ℕ} (θ θ' : Offspring J) (hJN : J ≤ N)
    (hq : θ.extinction < 1) (hq0 : 0 < θ.extinction)
    (hθ' : ∀ j, θ' j = θ.conjugateWeight j) (F : Finset (Word N))
    (hpc : ∀ v ∈ F, ∀ p : Word N, p <+: v → p ∈ F)
    (j k : Word N → ℕ) (𝒯 : Word N → ℕ → Set (Subtree N))
    (hj : ∀ u ∈ F, j u ≤ N) (hk : ∀ u ∈ F, k u ≠ 0)
    (hcomp : ∀ u ∈ F, ∀ i : Fin N, u ++ [i] ∈ F → (i : ℕ) < k u)
    (h𝒯 : ∀ u m, MeasurableSet (𝒯 u m)) :
    survivalMeasure (N := N) θ
        (⋂ u ∈ F, {c : Word N → ℕ | skelSub c u ∈ decorationEvent (j u) (k u)
            (fun m ↦ sample ⁻¹' 𝒯 u m)})
      = ∏ u ∈ F, (ENNReal.ofReal (θ (j u) * ((j u).choose (k u) : ℝ)
            * (1 - θ.extinction) ^ k u * θ.extinction ^ (j u - k u) / (1 - θ.extinction))
          * ∏ m ∈ Finset.range (j u - k u), treeLaw (N := N) θ' (𝒯 u m)) := sorry

/-- **The total progeny of a subcritical law has an exponential moment**: the
number of vertices of the sample is exponentially integrable. -/
theorem audit_progeny_exponential_moment {J N : ℕ} (θ : Offspring J) (hJN : J ≤ N)
    (h : θ.IsSubcritical) :
    ∃ σ : ℝ, 1 < σ ∧
      ∫⁻ c, ENNReal.ofReal σ ^ ((sample c : Set (Word N)).ncard)
        ∂(sampleMeasure (N := N) θ) < ⊤ := sorry

/-- **The hair separation**: a tree with hairs of unbounded depth is not
quasi-isometric to a tree all of whose vertices lie within a bounded distance of
a line. -/
theorem audit_hair_line_separation {V V' : Type*} {G : SimpleGraph V} {G' : SimpleGraph V'}
    {R : ℕ} (hG : G.IsTree) (hG' : G'.IsTree)
    (hhair : ∀ n : ℕ, ∃ (c : V) (P : Set V) (h : ℕ), n < h ∧ IsHair G c P h)
    (hline : ∀ u : V', ∃ (l : ℤ → V') (k : ℤ), IsLine G' l ∧ G'.dist u (l k) ≤ R) :
    ¬ QuasiIsometric G G' := sorry

/-- **The three-rays obstruction**: a tree carrying three rays that pairwise meet
only in their common initial vertex is not quasi-isometric to the ray. -/
theorem audit_three_rays {V : Type*} {G : SimpleGraph V} (hG : G.IsTree) {v : V}
    {ray : Fin 3 → ℕ → V} (hray : ∀ i, IsRay G (ray i)) (hbase : ∀ i, ray i 0 = v)
    (hmeet : ∀ i j, i ≠ j → ∀ m n, ray i m = ray j n → ray i m = v) :
    ¬ QuasiIsometric G rayGraph := sorry

end Challenge
